# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kutuphane.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1011, 660)
        MainWindow.setMinimumSize(QtCore.QSize(1011, 660))
        MainWindow.setMaximumSize(QtCore.QSize(1011, 660))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/books.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 80, 81, 81))
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/today.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(60, 60))
        self.pushButton.setCheckable(False)
        self.pushButton.setChecked(False)
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 170, 81, 81))
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 260, 81, 81))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 350, 81, 81))
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 440, 81, 81))
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/themes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(120, 20, 881, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(10, 200, 841, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(382, 19, 81, 91))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_3.setGeometry(QtCore.QRect(102, 47, 271, 31))
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(12, 47, 71, 31))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(12, 17, 101, 31))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(12, 81, 67, 31))
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_2.setGeometry(QtCore.QRect(102, 81, 271, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_6.setGeometry(QtCore.QRect(482, 21, 381, 111))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 131, 17))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 67, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 131, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(170, 30, 191, 17))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(170, 50, 171, 17))
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(170, 70, 161, 17))
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_27 = QtWidgets.QLabel(self.groupBox_6)
        self.label_27.setGeometry(QtCore.QRect(20, 90, 101, 17))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_6)
        self.label_28.setGeometry(QtCore.QRect(170, 90, 151, 17))
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(102, 17, 271, 27))
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(11)
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setCursorPosition(0)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_11.setGeometry(QtCore.QRect(382, 121, 81, 71))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(12)
        font.setItalic(True)
        self.pushButton_11.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        self.label_29.setGeometry(QtCore.QRect(502, 150, 211, 31))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_7.setGeometry(QtCore.QRect(12, 118, 361, 71))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_40 = QtWidgets.QLabel(self.groupBox_7)
        self.label_40.setGeometry(QtCore.QRect(40, 13, 31, 31))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_7)
        self.label_41.setGeometry(QtCore.QRect(90, 13, 31, 31))
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.label_39 = QtWidgets.QLabel(self.groupBox_7)
        self.label_39.setGeometry(QtCore.QRect(86, 36, 111, 31))
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.label_42 = QtWidgets.QLabel(self.groupBox_7)
        self.label_42.setGeometry(QtCore.QRect(40, 43, 41, 21))
        self.label_42.setObjectName("label_42")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_7.setGeometry(QtCore.QRect(220, 15, 121, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_12.setGeometry(QtCore.QRect(590, 530, 261, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_12.setObjectName("pushButton_12")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 851, 551))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_5.setGeometry(QtCore.QRect(10, 40, 801, 431))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(8)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(7, item)
        self.pushButton_30 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_30.setGeometry(QtCore.QRect(550, 480, 261, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_30.setObjectName("pushButton_30")
        self.label_46 = QtWidgets.QLabel(self.tab_7)
        self.label_46.setGeometry(QtCore.QRect(20, 480, 211, 31))
        self.label_46.setText("")
        self.label_46.setObjectName("label_46")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_6.setGeometry(QtCore.QRect(170, 140, 171, 31))
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(70, 190, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_7.setGeometry(QtCore.QRect(170, 190, 171, 31))
        self.comboBox_7.setEditable(True)
        self.comboBox_7.setObjectName("comboBox_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_8.setGeometry(QtCore.QRect(70, 390, 271, 61))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(70, 40, 61, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(70, 134, 91, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(70, 230, 81, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(390, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(70, 90, 91, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 40, 201, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_2.setGeometry(QtCore.QRect(390, 40, 351, 331))
        self.textEdit_2.setObjectName("textEdit_2")
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_8.setGeometry(QtCore.QRect(170, 240, 171, 31))
        self.comboBox_8.setEditable(True)
        self.comboBox_8.setObjectName("comboBox_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_6.setGeometry(QtCore.QRect(170, 290, 171, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(70, 290, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_25 = QtWidgets.QLabel(self.tab_5)
        self.label_25.setGeometry(QtCore.QRect(70, 340, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.spinBox = QtWidgets.QSpinBox(self.tab_5)
        self.spinBox.setGeometry(QtCore.QRect(170, 340, 171, 27))
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.comboBox = QtWidgets.QComboBox(self.tab_5)
        self.comboBox.setGeometry(QtCore.QRect(170, 90, 171, 27))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setGeometry(QtCore.QRect(350, 90, 21, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setGeometry(QtCore.QRect(350, 140, 21, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_5)
        self.label_32.setGeometry(QtCore.QRect(350, 190, 21, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_5)
        self.label_33.setGeometry(QtCore.QRect(350, 240, 21, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_5)
        self.label_34.setGeometry(QtCore.QRect(350, 40, 21, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.pushButton_31 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_31.setGeometry(QtCore.QRect(390, 390, 351, 61))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setObjectName("pushButton_31")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_9.setGeometry(QtCore.QRect(420, 400, 361, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_15 = QtWidgets.QLabel(self.tab_6)
        self.label_15.setGeometry(QtCore.QRect(420, 90, 101, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_6)
        self.label_16.setGeometry(QtCore.QRect(80, 160, 61, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_9.setGeometry(QtCore.QRect(180, 200, 191, 31))
        self.comboBox_9.setEditable(True)
        self.comboBox_9.setObjectName("comboBox_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(180, 160, 191, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_10.setGeometry(QtCore.QRect(180, 280, 191, 31))
        self.comboBox_10.setEditable(True)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_11.setGeometry(QtCore.QRect(180, 240, 191, 31))
        self.comboBox_11.setEditable(True)
        self.comboBox_11.setObjectName("comboBox_11")
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setGeometry(QtCore.QRect(80, 270, 81, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(80, 320, 111, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setGeometry(QtCore.QRect(80, 190, 91, 51))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_6)
        self.label_21.setGeometry(QtCore.QRect(80, 240, 71, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(210, 320, 161, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_43 = QtWidgets.QLabel(self.tab_6)
        self.label_43.setGeometry(QtCore.QRect(80, 120, 91, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.groupBox = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox.setGeometry(QtCore.QRect(60, 20, 731, 71))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_13.setGeometry(QtCore.QRect(530, 30, 191, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_5.setGeometry(QtCore.QRect(120, 30, 391, 31))
        self.comboBox_5.setEditable(True)
        self.comboBox_5.setObjectName("comboBox_5")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_14.setGeometry(QtCore.QRect(80, 400, 291, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.textEdit = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit.setGeometry(QtCore.QRect(420, 130, 361, 251))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit.setGeometry(QtCore.QRect(180, 120, 191, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_26 = QtWidgets.QLabel(self.tab_6)
        self.label_26.setGeometry(QtCore.QRect(80, 360, 111, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab_6)
        self.spinBox_2.setGeometry(QtCore.QRect(210, 360, 161, 31))
        self.spinBox_2.setObjectName("spinBox_2")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 10, 401, 531))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_21.setGeometry(QtCore.QRect(160, 100, 181, 31))
        self.lineEdit_21.setMouseTracking(True)
        self.lineEdit_21.setInputMask("")
        self.lineEdit_21.setMaxLength(32767)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_22.setGeometry(QtCore.QRect(160, 240, 181, 31))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_23.setGeometry(QtCore.QRect(160, 290, 181, 31))
        self.lineEdit_23.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_44 = QtWidgets.QLabel(self.groupBox_2)
        self.label_44.setGeometry(QtCore.QRect(20, 96, 101, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_15.setGeometry(QtCore.QRect(110, 380, 161, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_45 = QtWidgets.QLabel(self.groupBox_2)
        self.label_45.setGeometry(QtCore.QRect(20, 240, 101, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_47 = QtWidgets.QLabel(self.groupBox_2)
        self.label_47.setGeometry(QtCore.QRect(20, 290, 101, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_34.setGeometry(QtCore.QRect(160, 144, 181, 31))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.label_57 = QtWidgets.QLabel(self.groupBox_2)
        self.label_57.setGeometry(QtCore.QRect(20, 140, 101, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_35.setGeometry(QtCore.QRect(160, 190, 181, 31))
        self.lineEdit_35.setText("")
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.label_58 = QtWidgets.QLabel(self.groupBox_2)
        self.label_58.setGeometry(QtCore.QRect(20, 190, 131, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(120, 340, 151, 20))
        self.label_17.setText("")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(360, 100, 21, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(360, 140, 21, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(360, 190, 21, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(360, 240, 21, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(470, 10, 361, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_48 = QtWidgets.QLabel(self.groupBox_3)
        self.label_48.setGeometry(QtCore.QRect(20, 36, 101, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_26.setEnabled(True)
        self.lineEdit_26.setGeometry(QtCore.QRect(150, 40, 181, 31))
        self.lineEdit_26.setInputMask("")
        self.lineEdit_26.setMaxLength(32767)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 100, 311, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setEnabled(False)
        self.groupBox_5.setGeometry(QtCore.QRect(470, 180, 361, 361))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_30.setGeometry(QtCore.QRect(160, 190, 171, 31))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_17.setGeometry(QtCore.QRect(20, 270, 311, 31))
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_52 = QtWidgets.QLabel(self.groupBox_5)
        self.label_52.setGeometry(QtCore.QRect(20, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_51 = QtWidgets.QLabel(self.groupBox_5)
        self.label_51.setGeometry(QtCore.QRect(20, 190, 101, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_29.setGeometry(QtCore.QRect(160, 110, 171, 31))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_59 = QtWidgets.QLabel(self.groupBox_5)
        self.label_59.setGeometry(QtCore.QRect(20, 150, 131, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_36.setGeometry(QtCore.QRect(160, 150, 171, 31))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.label_60 = QtWidgets.QLabel(self.groupBox_5)
        self.label_60.setGeometry(QtCore.QRect(20, 70, 111, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_37.setGeometry(QtCore.QRect(160, 70, 171, 31))
        self.lineEdit_37.setInputMask("")
        self.lineEdit_37.setMaxLength(32767)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_38.setGeometry(QtCore.QRect(160, 230, 171, 31))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.label_53 = QtWidgets.QLabel(self.groupBox_5)
        self.label_53.setGeometry(QtCore.QRect(20, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(12)
        font.setItalic(True)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_26.setGeometry(QtCore.QRect(20, 310, 311, 31))
        self.pushButton_26.setObjectName("pushButton_26")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_4.setGeometry(QtCore.QRect(10, 20, 851, 531))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_20.setGeometry(QtCore.QRect(550, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setItalic(True)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_56 = QtWidgets.QLabel(self.tab_13)
        self.label_56.setGeometry(QtCore.QRect(16, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_13)
        self.tableWidget_4.setGeometry(QtCore.QRect(20, 70, 811, 411))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_33.setGeometry(QtCore.QRect(150, 20, 371, 31))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_27.setGeometry(QtCore.QRect(730, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setItalic(True)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.tabWidget_4.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_19.setGeometry(QtCore.QRect(500, 20, 191, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setItalic(True)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_55 = QtWidgets.QLabel(self.tab_14)
        self.label_55.setGeometry(QtCore.QRect(16, 19, 101, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_14)
        self.tableWidget_3.setGeometry(QtCore.QRect(20, 70, 801, 411))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_32.setGeometry(QtCore.QRect(120, 20, 371, 31))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_29.setGeometry(QtCore.QRect(700, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setItalic(True)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName("pushButton_29")
        self.tabWidget_4.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_15)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 70, 801, 411))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_18.setGeometry(QtCore.QRect(528, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setItalic(True)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.tab_15)
        self.lineEdit_31.setGeometry(QtCore.QRect(150, 20, 371, 31))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_54 = QtWidgets.QLabel(self.tab_15)
        self.label_54.setGeometry(QtCore.QRect(16, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(14)
        font.setItalic(True)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_28.setGeometry(QtCore.QRect(720, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setItalic(True)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.tabWidget_4.addTab(self.tab_15, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setEnabled(True)
        self.groupBox_4.setGeometry(QtCore.QRect(210, 0, 371, 631))
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_21.setGeometry(QtCore.QRect(80, 170, 111, 101))
        self.pushButton_21.setStyleSheet("background-color: rgb(48, 47, 47);")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_22.setGeometry(QtCore.QRect(200, 170, 111, 101))
        self.pushButton_22.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_23.setGeometry(QtCore.QRect(80, 280, 111, 101))
        self.pushButton_23.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_24.setGeometry(QtCore.QRect(200, 280, 111, 101))
        self.pushButton_24.setStyleSheet("background-color: rgb(25, 35, 45);")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_25.setGeometry(QtCore.QRect(10, 250, 31, 41))
        self.pushButton_25.setObjectName("pushButton_25")
        self.tabWidget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.groupBox_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_4.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_2, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.tableWidget_5)
        MainWindow.setTabOrder(self.tableWidget_5, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.comboBox_6)
        MainWindow.setTabOrder(self.comboBox_6, self.comboBox_7)
        MainWindow.setTabOrder(self.comboBox_7, self.comboBox_8)
        MainWindow.setTabOrder(self.comboBox_8, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.spinBox)
        MainWindow.setTabOrder(self.spinBox, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.comboBox_5)
        MainWindow.setTabOrder(self.comboBox_5, self.pushButton_13)
        MainWindow.setTabOrder(self.pushButton_13, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_7)
        MainWindow.setTabOrder(self.lineEdit_7, self.comboBox_9)
        MainWindow.setTabOrder(self.comboBox_9, self.comboBox_11)
        MainWindow.setTabOrder(self.comboBox_11, self.comboBox_10)
        MainWindow.setTabOrder(self.comboBox_10, self.lineEdit_9)
        MainWindow.setTabOrder(self.lineEdit_9, self.spinBox_2)
        MainWindow.setTabOrder(self.spinBox_2, self.pushButton_9)
        MainWindow.setTabOrder(self.pushButton_9, self.pushButton_14)
        MainWindow.setTabOrder(self.pushButton_14, self.lineEdit_21)
        MainWindow.setTabOrder(self.lineEdit_21, self.lineEdit_34)
        MainWindow.setTabOrder(self.lineEdit_34, self.lineEdit_35)
        MainWindow.setTabOrder(self.lineEdit_35, self.lineEdit_22)
        MainWindow.setTabOrder(self.lineEdit_22, self.lineEdit_23)
        MainWindow.setTabOrder(self.lineEdit_23, self.pushButton_15)
        MainWindow.setTabOrder(self.pushButton_15, self.lineEdit_26)
        MainWindow.setTabOrder(self.lineEdit_26, self.pushButton_16)
        MainWindow.setTabOrder(self.pushButton_16, self.lineEdit_37)
        MainWindow.setTabOrder(self.lineEdit_37, self.lineEdit_29)
        MainWindow.setTabOrder(self.lineEdit_29, self.lineEdit_36)
        MainWindow.setTabOrder(self.lineEdit_36, self.lineEdit_30)
        MainWindow.setTabOrder(self.lineEdit_30, self.lineEdit_38)
        MainWindow.setTabOrder(self.lineEdit_38, self.pushButton_17)
        MainWindow.setTabOrder(self.pushButton_17, self.lineEdit_33)
        MainWindow.setTabOrder(self.lineEdit_33, self.pushButton_20)
        MainWindow.setTabOrder(self.pushButton_20, self.tableWidget_4)
        MainWindow.setTabOrder(self.tableWidget_4, self.lineEdit_32)
        MainWindow.setTabOrder(self.lineEdit_32, self.pushButton_19)
        MainWindow.setTabOrder(self.pushButton_19, self.tableWidget_3)
        MainWindow.setTabOrder(self.tableWidget_3, self.lineEdit_31)
        MainWindow.setTabOrder(self.lineEdit_31, self.pushButton_18)
        MainWindow.setTabOrder(self.pushButton_18, self.tableWidget_2)
        MainWindow.setTabOrder(self.tableWidget_2, self.tabWidget_2)
        MainWindow.setTabOrder(self.tabWidget_2, self.pushButton_21)
        MainWindow.setTabOrder(self.pushButton_21, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.tabWidget_4)
        MainWindow.setTabOrder(self.tabWidget_4, self.pushButton_22)
        MainWindow.setTabOrder(self.pushButton_22, self.pushButton_23)
        MainWindow.setTabOrder(self.pushButton_23, self.pushButton_24)
        MainWindow.setTabOrder(self.pushButton_24, self.pushButton_25)
        MainWindow.setTabOrder(self.pushButton_25, self.textEdit_2)
        MainWindow.setTabOrder(self.textEdit_2, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kütüphane"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ISBN"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Kitap Adı"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Durum"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Öğrenci Adı "))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Öğrenci Tc"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Alınan Tarih"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Teslim Tarihi"))
        self.pushButton_6.setText(_translate("MainWindow", "Ekle"))
        self.label.setText(_translate("MainWindow", "Kitap Seç"))
        self.label_4.setText(_translate("MainWindow", "Öğrenci Tc "))
        self.label_3.setText(_translate("MainWindow", "Gün"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "14"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Öğrenci Bilgileri"))
        self.label_2.setText(_translate("MainWindow", "Öğrenci adı soyadı"))
        self.label_5.setText(_translate("MainWindow", "Email"))
        self.label_6.setText(_translate("MainWindow", "Öğrenci tel no"))
        self.label_27.setText(_translate("MainWindow", "Öğrenci Tc no"))
        self.pushButton_11.setText(_translate("MainWindow", "Yenile"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Sil"))
        self.label_40.setText(_translate("MainWindow", "ID"))
        self.label_42.setText(_translate("MainWindow", "ISBN"))
        self.pushButton_7.setText(_translate("MainWindow", "Sil"))
        self.pushButton_12.setText(_translate("MainWindow", "Excel Çıkar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ISBN"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kitap Adı"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Kitabın Yazarı"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Kategori"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Yayınevi"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Açıklama"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Sayfa Sayısı"))
        item = self.tableWidget_5.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Adet"))
        self.pushButton_30.setText(_translate("MainWindow", "Excel Çıkar"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Tüm Kitaplar"))
        self.label_11.setText(_translate("MainWindow", "Yazar"))
        self.pushButton_8.setText(_translate("MainWindow", "Ekle"))
        self.label_8.setText(_translate("MainWindow", "ISBN"))
        self.label_10.setText(_translate("MainWindow", "Kategori"))
        self.label_12.setText(_translate("MainWindow", "Yayınevi"))
        self.label_13.setText(_translate("MainWindow", "Açıklama"))
        self.label_9.setText(_translate("MainWindow", "Kitap Adı"))
        self.label_14.setText(_translate("MainWindow", "Sayfa "))
        self.label_25.setText(_translate("MainWindow", "Adet"))
        self.spinBox.setSpecialValueText(_translate("MainWindow", "1"))
        self.label_30.setText(_translate("MainWindow", "*"))
        self.label_31.setText(_translate("MainWindow", "*"))
        self.label_32.setText(_translate("MainWindow", "*"))
        self.label_33.setText(_translate("MainWindow", "*"))
        self.label_34.setText(_translate("MainWindow", "*"))
        self.pushButton_31.setText(_translate("MainWindow", "Barkod Oku"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Yeni Kitap Ekle"))
        self.pushButton_9.setText(_translate("MainWindow", "Düzenle"))
        self.label_15.setText(_translate("MainWindow", "Açıklama"))
        self.label_16.setText(_translate("MainWindow", "ISBN"))
        self.label_18.setText(_translate("MainWindow", "Yayınevi"))
        self.label_19.setText(_translate("MainWindow", "Sayfa Sayısı"))
        self.label_20.setText(_translate("MainWindow", "Kategori"))
        self.label_21.setText(_translate("MainWindow", "Yazar"))
        self.label_43.setText(_translate("MainWindow", "Kitap Adı"))
        self.groupBox.setTitle(_translate("MainWindow", "Kitap Ara"))
        self.pushButton_13.setText(_translate("MainWindow", "Ara"))
        self.label_22.setText(_translate("MainWindow", "Kitap Adı"))
        self.pushButton_14.setText(_translate("MainWindow", "Sil"))
        self.label_26.setText(_translate("MainWindow", "Adet"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Düzenle Veya Sil"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Yeni Kullanıcı"))
        self.lineEdit_23.setInputMask(_translate("MainWindow", "(999) 999 99 99"))
        self.label_44.setText(_translate("MainWindow", "Öğrenci Tc"))
        self.pushButton_15.setText(_translate("MainWindow", "Yeni Öğrenci Ekle"))
        self.label_45.setText(_translate("MainWindow", "E-mail"))
        self.label_47.setText(_translate("MainWindow", "Telefon No"))
        self.label_57.setText(_translate("MainWindow", "Öğrenci Adı"))
        self.label_58.setText(_translate("MainWindow", "Öğrenci Soyadı"))
        self.label_35.setText(_translate("MainWindow", "*"))
        self.label_36.setText(_translate("MainWindow", "*"))
        self.label_37.setText(_translate("MainWindow", "*"))
        self.label_38.setText(_translate("MainWindow", "*"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Giriş Yap"))
        self.label_48.setText(_translate("MainWindow", "Öğrenci Tc"))
        self.pushButton_16.setText(_translate("MainWindow", "Giriş Yap"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Öğrenci Bilgileri Düzenle"))
        self.pushButton_17.setText(_translate("MainWindow", "Düzenle"))
        self.label_52.setText(_translate("MainWindow", "Öğrenci Adı"))
        self.label_51.setText(_translate("MainWindow", "E-mail"))
        self.label_59.setText(_translate("MainWindow", "Öğrenci Soyadı"))
        self.label_60.setText(_translate("MainWindow", "Tc No"))
        self.lineEdit_38.setInputMask(_translate("MainWindow", "(999) 999 99 99"))
        self.label_53.setText(_translate("MainWindow", "Telefon  No"))
        self.pushButton_26.setText(_translate("MainWindow", "Sil"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Page"))
        self.pushButton_20.setText(_translate("MainWindow", "Ekle"))
        self.label_56.setText(_translate("MainWindow", "Kategori Adı"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Kategori"))
        self.pushButton_27.setText(_translate("MainWindow", "Sil"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("MainWindow", "Kategori"))
        self.pushButton_19.setText(_translate("MainWindow", "Ekle"))
        self.label_55.setText(_translate("MainWindow", "Yazar Adı"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Yazar"))
        self.pushButton_29.setText(_translate("MainWindow", "Sil"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14), _translate("MainWindow", "Yazar"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Yayınevi"))
        self.pushButton_18.setText(_translate("MainWindow", "Ekle"))
        self.label_54.setText(_translate("MainWindow", "Yayınevi Adı"))
        self.pushButton_28.setText(_translate("MainWindow", "Sil"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_15), _translate("MainWindow", "Yayınevi"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Tema Seç"))
        self.pushButton_21.setText(_translate("MainWindow", "Koyu Mavi"))
        self.pushButton_22.setText(_translate("MainWindow", "Koyu Gri"))
        self.pushButton_23.setText(_translate("MainWindow", "Koyu Turuncu"))
        self.pushButton_24.setText(_translate("MainWindow", "Koyu"))
        self.pushButton_25.setText(_translate("MainWindow", ">"))
import icon_rc
